export const TASK_CREATING_ACTION = 'TASK_CREATING';
export const TASK_SELECT_ACTION = 'TASK_SELECT';
export const REMIND_ACTION = 'REMIND';
export const TASK_UNDER_ACTION = 'TASK_UNDER_ACTION';
export const POSTPONE_TASK = 'POSTPONE_TASK';
