export const BUSINESS_ERROR = {
    ZERO_PRIORITY: 'ZERO_PRIORITY',
    TOO_HIGH_PRIORITY: 'TOO_HIGH_PRIORITY',
    CANNOT_CREATE_NOTIFICATION_TASK_IS_DONE: 'CANNOT_CREATE_NOTIFICATION_TASK_IS_DONE',
    NO_USER_IDENTIFIER: 'NO_USER_IDENTIFIER',
    UNRECOGNIZED_ANSWER: 'UNRECOGNIZED_ANSWER',
    ANSWER_IS_SETTED: 'ANSWER_IS_SETTED',
    INCORRECT_TIMEZONE: 'INCORRECT_TIMEZONE',
    END_TIME_LESS_THAN_START: 'END_TIME_LESS_THAN_START',
    USER_IS_NOT_DEFINED: 'USER_IS_NOT_DEFINED',
    INCREASE_NOTIFICATION_NOT_POSITIVE: 'INCREASE_NOTIFICATION_NOT_POSITIVE',
    DECREASE_NOTIFICATION_NOT_POSITIVE: 'DECREASE_NOTIFICATION_NOT_POSITIVE',
}

export const USER_STORY_ERROR = {
    USER_BANNED: 'USER_BANNED',
    USER_DOESNT_EXISTS: 'USER_DOESNT_EXISTS',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',

}

export const REPOSITORY_ERROR = {
    DTO_NOT_CONSISTENT: 'DTO_NOT_CONSISTENT',

}

export const DTO_ERROR = {
    DATA_IS_NOT_CONSISTENCE: 'DATA_IS_NOT_CONSISTENCE',
    TOO_LONG_NAME: 'TOO_LONG_NAME',
    WRONG_ANSWER: 'WRONG_ANSWER',
    START_TIME_WRONG_FORMAT: 'START_TIME_WRONG_FORMAT',
    EMPTY_USER_ID: 'EMPTY_USER_ID',
    END_TIME_LESS_THAN_START: 'END_TIME_LESS_THAN_START'
}

export const SETTER_ERRORS = {
    DATA_IS_NOT_VALID: 'DATA_IS_NOT_VALID',
    VALUE_MUST_BE_POSITIVE: 'VALUE_MUST_BE_POSITIVE',
    TARGET_TYPE: 'TARGET_TYPE',
    VALUE_MUST_BE: 'VALUE_MUST_BE'
}
